[run]
init_cmds = [
	["go", "install"],
	["go", "build"],
	["./$APP_NAME"]
]									# Commands run in start
watch_all = true					# Watch all sub-directories
watch_dirs = []						# Directories to watch
watch_exts = [".go",".ini"]				# Extensions to watch
ignore = [".git", "node_modules", ".idea"] 	# Directories to exclude from watching
ignore_files = []					# Regexps for ignoring specific notifies
build_delay = 1500					# Minimal interval to Trigger build event
interrupt_timout = 15				# Time to wait until force kill
cmds = [
	["go", "install"],
	["go", "build"],
	["./$APP_NAME"]
]									# Commands to run

[sync]
listen_addr = ":5050"
remote_addr = ":5050"